import Head from "next/head";
import Layout from "../components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/avatar-index.jpg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import TransitionEffect from "@/components/TransitionEffect";
export default function Home() {
  return (
    <>
      <Head>
        <title>Phạm Gia Huy | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="shortcut icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Eo_circle_blue_letter-p.svg/480px-Eo_circle_blue_letter-p.svg.png"
        />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full md:block">
            <div className="w-1/2 md:w-[100%]">
              <div className="myCard">
                <h3>Hire me </h3>
                <Image
                  priority
                  src={profilePic}
                  alt="phamgiahuy"
                  className="w-full h-auto max-w-[360px] rounded-3xl mx-auto myAvatar"
                />
              </div>
              {/* <a href="https://mythrillfiction.com/" target="_blank">Mythrill</a> */}
            </div>
            <div className="w-1/2 md:w-full flex flex-col items-center text-left mt-5">
              <p className=" w-full text-sm relative pl-8 dark:text-light">
                Hello
                <span
                  className={`h-[1px] inline-block bg-black absolute left-0  bottom-2 
              transition-[width] ease duration-300 w-5 dark:bg-light`}
                >
                  &nbsp;
                </span>
              </p>
              <AnimatedText
                text={`My name is Pham Gia huy. `}
                className="!text-6xl !text-left lg:!text-5xl md:!text-4xl sm:!text-3xl "
              />
              <p className="text-base font-medium my-4 !text-left w-full dark:text-light">
                I am Full Stack Developer who can build you full-stack web apps
                with React.js ecosystem for Frontend Web Development and Node.js
                ecosystem for Backend API Development (REST API).
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  className="flex items-center bg-dark text-light py-2.5 px-6 rounded-lg font-semibold hover:bg-light hover:text-dark duration-300 border border-dark dark:bg-light dark:border-light dark:text-dark"
                  // download={true}
                  href="/PhamGiaHuy_FrontEnd.pdf"
                  target="_blank"
                >
                  Resume
                  <LinkArrow className="w-5 ml-1" />
                </Link>
                <Link
                  href="mailto:pgiahuy653@gmail.com"
                  target="_blank"
                  className="font-semibold hover:underline ml-6
                dark:text-light
                "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
